### PR TITLE
Update Apache Virtualhost

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This PR proposes a new Apache VirtualHost configuration.

It enables SSL, for security reasons, thus closing https://github.com/sabre-io/Baikal/issues/338.
Also for security concerns, it get rid of .htaccess files, closing https://github.com/sabre-io/Baikal/issues/738.

Thank you 👍

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
Please squash the commits for the Sake of a clean git history. THX

**Comment by benrubson** [comment]
I thought you could have squash-merged :)
Anyway, here it is.
Thx 👍

**Comment by ByteHamster** [comment]
Are you sure that `Options None` instead of `Options +FollowSymlinks` works? There are symlinks in `/var/www/baikal/html`.

**Comment by benrubson** [comment]
Yes, this is how I use it :)
Strangely, I can't find any symlink in `baikal/html`.
`Options +FollowSymlinks` was needed for `RewriteRule` options in .htaccess files, without Apache raises an error.

**Comment by ByteHamster** [comment]
Looks like you modified the default setup. Have a look at the following link. The `index.php` file is a symlink to `Core/Frameworks/BaikalAdmin/WWWRoot/index.php`.
https://github.com/sabre-io/Baikal/tree/master/html/admin

**Comment by benrubson** [comment]
I installed using the .zip release archive.
There are only plain files in it.

**Comment by ByteHamster** [comment]
Oh okay you are right. Looks like I have never actually used a release file and always just cloned the repo

**Comment by DeepDiver1975** [comment]
> always just cloned the repo

which is a valid installation method from my pov. Will it work with this Apache config?

**Comment by benrubson** [comment]
> Will it work with this Apache config?

No, I then modified the config adding this specific case.
As installation procedure uses .zip release archive, I leave this commented-out, for security concerns.

**Comment by benrubson** [comment]
Let's think about merging this please ?
Many thx 👍

**Pull request merged**
